version: '3.8'
services:
   db:    
      image: mysql:5.7.16
      container_name: mysql_fsquare
      ports:
         - '3306:3306'      
      environment:
         - MYSQL_ROOT_USER=myuser
         - MYSQL_ROOT_PASSWORD=secret
         - MYSQL_DATABASE=my_db 
      volumes:         
         - ${PWD}/data/db_data:/var/lib/mysql:rw
         - ${PWD}/data/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
     

   app:
     build: 
        context: .
        dockerfile: Dockerfile
     image: jupyter-lab
     container_name: recommendation-sys-container 
     links:
            - "db"       
     ports:
            - "8888:8888"
     volumes:
      - ${PWD}/app:/usr/src/app
     # mantém o container aberto, se o mesmo não executa um script
     tty: true
